# Automatically generated by zsh setup doodads

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=**'
zstyle ':completion:*' max-errors 1
zstyle ':completion:*' menu select=3
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename '/home/nick/.zshrc'

autoload -Uz compinit && compinit
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
unsetopt beep nomatch

# Clumsily hacked-together settings that probably don't work

autoload -Uz colors && colors
export NCURSES_NO_UTF8_ACS=1
export CLICOLOR=1
if [ ! $LS_COLORS ] && [ -e ~/dotfiles/dircolors ] && [ ! type dircolors &> /dev/null ]; then
    eval "$(dircolors ~/dotfiles/dircolors)"
fi

if [ -d ~/.pyenv ]; then
	export PYENV_ROOT="$HOME/.pyenv"
	export PATH="$PYENV_ROOT/bin:$PATH"
	export PYENV_VIRTUALENV_DISABLE_PROMPT=1
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
fi

function parse_git_branch () {
	git branch 2> /dev/null | grep "*" | sed -e 's/^* \(.*\)/ (\1)/'
}

function inside_virtual_env () {
	if [ $(pyenv version-name) != "system" ]; then
		echo "•"
	else
		echo " "
	fi
}

function precmd() {
	export RPROMPT="%~$(parse_git_branch)"
	export PROMPT="%K{white}%F{black}$(inside_virtual_env)%f%k %F{white}%n@%m %B%(!.#.›)%b%f "
}

# Aliases

function csv() {
	csvtool readable $1 | sort | less -inS
}

if [[ `uname` == "Linux" ]] then
    alias ls='ls --color=auto --time-style=iso'
fi
alias grep='grep --color=auto'
alias ll='ls -lhF'
alias la='ls -a'


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
